'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace com.appfacturainteligente
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="soapHttpEndpoint", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WSCFDI33
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private TimbrarCFDIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelarCFDIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelacionAsincronaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EstatusCancelacionAsincronaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtenerPDFOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtenerAcuseEnvioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtenerAcuseCancelacionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CambiarPasswordOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarComplementoTimbreOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarTimbrePorReferenciaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarCreditosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarComprobantesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.GeneraRecibo33.My.MySettings.Default.GeneraRecibo33_com_appfacturainteligente_WSCFDI33
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event TimbrarCFDICompleted As TimbrarCFDICompletedEventHandler
        
        '''<remarks/>
        Public Event CancelarCFDICompleted As CancelarCFDICompletedEventHandler
        
        '''<remarks/>
        Public Event CancelacionAsincronaCompleted As CancelacionAsincronaCompletedEventHandler
        
        '''<remarks/>
        Public Event EstatusCancelacionAsincronaCompleted As EstatusCancelacionAsincronaCompletedEventHandler
        
        '''<remarks/>
        Public Event ObtenerPDFCompleted As ObtenerPDFCompletedEventHandler
        
        '''<remarks/>
        Public Event ObtenerAcuseEnvioCompleted As ObtenerAcuseEnvioCompletedEventHandler
        
        '''<remarks/>
        Public Event ObtenerAcuseCancelacionCompleted As ObtenerAcuseCancelacionCompletedEventHandler
        
        '''<remarks/>
        Public Event CambiarPasswordCompleted As CambiarPasswordCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarComplementoTimbreCompleted As ConsultarComplementoTimbreCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarTimbrePorReferenciaCompleted As ConsultarTimbrePorReferenciaCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarCreditosCompleted As ConsultarCreditosCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarComprobantesCompleted As ConsultarComprobantesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/TimbrarCFDI", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TimbrarCFDI(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal cadenaXML As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal referencia As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaTFD33
            Dim results() As Object = Me.Invoke("TimbrarCFDI", New Object() {usuario, password, cadenaXML, referencia})
            Return CType(results(0),RespuestaTFD33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TimbrarCFDIAsync(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String, ByVal referencia As String)
            Me.TimbrarCFDIAsync(usuario, password, cadenaXML, referencia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TimbrarCFDIAsync(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String, ByVal referencia As String, ByVal userState As Object)
            If (Me.TimbrarCFDIOperationCompleted Is Nothing) Then
                Me.TimbrarCFDIOperationCompleted = AddressOf Me.OnTimbrarCFDIOperationCompleted
            End If
            Me.InvokeAsync("TimbrarCFDI", New Object() {usuario, password, cadenaXML, referencia}, Me.TimbrarCFDIOperationCompleted, userState)
        End Sub
        
        Private Sub OnTimbrarCFDIOperationCompleted(ByVal arg As Object)
            If (Not (Me.TimbrarCFDICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TimbrarCFDICompleted(Me, New TimbrarCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/CancelarCFDI", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelarCFDI(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal rFCEmisor As String, <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")> ByVal listaCFDI() As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clavePrivada_Base64 As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal passwordClavePrivada As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaCancelacion
            Dim results() As Object = Me.Invoke("CancelarCFDI", New Object() {usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada})
            Return CType(results(0),RespuestaCancelacion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarCFDIAsync(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String)
            Me.CancelarCFDIAsync(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarCFDIAsync(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String, ByVal userState As Object)
            If (Me.CancelarCFDIOperationCompleted Is Nothing) Then
                Me.CancelarCFDIOperationCompleted = AddressOf Me.OnCancelarCFDIOperationCompleted
            End If
            Me.InvokeAsync("CancelarCFDI", New Object() {usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada}, Me.CancelarCFDIOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarCFDIOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarCFDICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarCFDICompleted(Me, New CancelarCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/CancelacionAsincrona", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelacionAsincrona(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal rFCEmisor As String, <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")> ByVal listaCFDI() As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clavePrivada_Base64 As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal passwordClavePrivada As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaCancelacionAsincrona
            Dim results() As Object = Me.Invoke("CancelacionAsincrona", New Object() {usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada})
            Return CType(results(0),RespuestaCancelacionAsincrona)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelacionAsincronaAsync(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String)
            Me.CancelacionAsincronaAsync(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelacionAsincronaAsync(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String, ByVal userState As Object)
            If (Me.CancelacionAsincronaOperationCompleted Is Nothing) Then
                Me.CancelacionAsincronaOperationCompleted = AddressOf Me.OnCancelacionAsincronaOperationCompleted
            End If
            Me.InvokeAsync("CancelacionAsincrona", New Object() {usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada}, Me.CancelacionAsincronaOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelacionAsincronaOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelacionAsincronaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelacionAsincronaCompleted(Me, New CancelacionAsincronaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/EstatusCancelacionAsincrona", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EstatusCancelacionAsincrona(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal referencia As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaEstatusCancelacionAsincrona
            Dim results() As Object = Me.Invoke("EstatusCancelacionAsincrona", New Object() {usuario, password, referencia})
            Return CType(results(0),RespuestaEstatusCancelacionAsincrona)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EstatusCancelacionAsincronaAsync(ByVal usuario As String, ByVal password As String, ByVal referencia As String)
            Me.EstatusCancelacionAsincronaAsync(usuario, password, referencia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EstatusCancelacionAsincronaAsync(ByVal usuario As String, ByVal password As String, ByVal referencia As String, ByVal userState As Object)
            If (Me.EstatusCancelacionAsincronaOperationCompleted Is Nothing) Then
                Me.EstatusCancelacionAsincronaOperationCompleted = AddressOf Me.OnEstatusCancelacionAsincronaOperationCompleted
            End If
            Me.InvokeAsync("EstatusCancelacionAsincrona", New Object() {usuario, password, referencia}, Me.EstatusCancelacionAsincronaOperationCompleted, userState)
        End Sub
        
        Private Sub OnEstatusCancelacionAsincronaOperationCompleted(ByVal arg As Object)
            If (Not (Me.EstatusCancelacionAsincronaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EstatusCancelacionAsincronaCompleted(Me, New EstatusCancelacionAsincronaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/ObtenerPDF", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtenerPDF(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal uUID As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal LogoBase64 As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaTFD33
            Dim results() As Object = Me.Invoke("ObtenerPDF", New Object() {usuario, password, uUID, LogoBase64})
            Return CType(results(0),RespuestaTFD33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtenerPDFAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String, ByVal LogoBase64 As String)
            Me.ObtenerPDFAsync(usuario, password, uUID, LogoBase64, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtenerPDFAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String, ByVal LogoBase64 As String, ByVal userState As Object)
            If (Me.ObtenerPDFOperationCompleted Is Nothing) Then
                Me.ObtenerPDFOperationCompleted = AddressOf Me.OnObtenerPDFOperationCompleted
            End If
            Me.InvokeAsync("ObtenerPDF", New Object() {usuario, password, uUID, LogoBase64}, Me.ObtenerPDFOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtenerPDFOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtenerPDFCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtenerPDFCompleted(Me, New ObtenerPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/ObtenerAcuseEnvio", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtenerAcuseEnvio(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal uUID As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaTFD33
            Dim results() As Object = Me.Invoke("ObtenerAcuseEnvio", New Object() {usuario, password, uUID})
            Return CType(results(0),RespuestaTFD33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtenerAcuseEnvioAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String)
            Me.ObtenerAcuseEnvioAsync(usuario, password, uUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtenerAcuseEnvioAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String, ByVal userState As Object)
            If (Me.ObtenerAcuseEnvioOperationCompleted Is Nothing) Then
                Me.ObtenerAcuseEnvioOperationCompleted = AddressOf Me.OnObtenerAcuseEnvioOperationCompleted
            End If
            Me.InvokeAsync("ObtenerAcuseEnvio", New Object() {usuario, password, uUID}, Me.ObtenerAcuseEnvioOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtenerAcuseEnvioOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtenerAcuseEnvioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtenerAcuseEnvioCompleted(Me, New ObtenerAcuseEnvioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/ObtenerAcuseCancelacion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtenerAcuseCancelacion(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal uUID As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaTFD33
            Dim results() As Object = Me.Invoke("ObtenerAcuseCancelacion", New Object() {usuario, password, uUID})
            Return CType(results(0),RespuestaTFD33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtenerAcuseCancelacionAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String)
            Me.ObtenerAcuseCancelacionAsync(usuario, password, uUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtenerAcuseCancelacionAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String, ByVal userState As Object)
            If (Me.ObtenerAcuseCancelacionOperationCompleted Is Nothing) Then
                Me.ObtenerAcuseCancelacionOperationCompleted = AddressOf Me.OnObtenerAcuseCancelacionOperationCompleted
            End If
            Me.InvokeAsync("ObtenerAcuseCancelacion", New Object() {usuario, password, uUID}, Me.ObtenerAcuseCancelacionOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtenerAcuseCancelacionOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtenerAcuseCancelacionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtenerAcuseCancelacionCompleted(Me, New ObtenerAcuseCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/CambiarPassword", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CambiarPassword(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal passwordActual As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal passwordNuevo As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaTFD33
            Dim results() As Object = Me.Invoke("CambiarPassword", New Object() {usuario, passwordActual, passwordNuevo})
            Return CType(results(0),RespuestaTFD33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CambiarPasswordAsync(ByVal usuario As String, ByVal passwordActual As String, ByVal passwordNuevo As String)
            Me.CambiarPasswordAsync(usuario, passwordActual, passwordNuevo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CambiarPasswordAsync(ByVal usuario As String, ByVal passwordActual As String, ByVal passwordNuevo As String, ByVal userState As Object)
            If (Me.CambiarPasswordOperationCompleted Is Nothing) Then
                Me.CambiarPasswordOperationCompleted = AddressOf Me.OnCambiarPasswordOperationCompleted
            End If
            Me.InvokeAsync("CambiarPassword", New Object() {usuario, passwordActual, passwordNuevo}, Me.CambiarPasswordOperationCompleted, userState)
        End Sub
        
        Private Sub OnCambiarPasswordOperationCompleted(ByVal arg As Object)
            If (Not (Me.CambiarPasswordCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CambiarPasswordCompleted(Me, New CambiarPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/ConsultarComplementoTimbre", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarComplementoTimbre(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal uUID As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaTFD33
            Dim results() As Object = Me.Invoke("ConsultarComplementoTimbre", New Object() {usuario, password, uUID})
            Return CType(results(0),RespuestaTFD33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarComplementoTimbreAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String)
            Me.ConsultarComplementoTimbreAsync(usuario, password, uUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarComplementoTimbreAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String, ByVal userState As Object)
            If (Me.ConsultarComplementoTimbreOperationCompleted Is Nothing) Then
                Me.ConsultarComplementoTimbreOperationCompleted = AddressOf Me.OnConsultarComplementoTimbreOperationCompleted
            End If
            Me.InvokeAsync("ConsultarComplementoTimbre", New Object() {usuario, password, uUID}, Me.ConsultarComplementoTimbreOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarComplementoTimbreOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarComplementoTimbreCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarComplementoTimbreCompleted(Me, New ConsultarComplementoTimbreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/ConsultarTimbrePorReferencia", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarTimbrePorReferencia(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal referencia As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaTFD33
            Dim results() As Object = Me.Invoke("ConsultarTimbrePorReferencia", New Object() {usuario, password, referencia})
            Return CType(results(0),RespuestaTFD33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarTimbrePorReferenciaAsync(ByVal usuario As String, ByVal password As String, ByVal referencia As String)
            Me.ConsultarTimbrePorReferenciaAsync(usuario, password, referencia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarTimbrePorReferenciaAsync(ByVal usuario As String, ByVal password As String, ByVal referencia As String, ByVal userState As Object)
            If (Me.ConsultarTimbrePorReferenciaOperationCompleted Is Nothing) Then
                Me.ConsultarTimbrePorReferenciaOperationCompleted = AddressOf Me.OnConsultarTimbrePorReferenciaOperationCompleted
            End If
            Me.InvokeAsync("ConsultarTimbrePorReferencia", New Object() {usuario, password, referencia}, Me.ConsultarTimbrePorReferenciaOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarTimbrePorReferenciaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarTimbrePorReferenciaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarTimbrePorReferenciaCompleted(Me, New ConsultarTimbrePorReferenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/ConsultarCreditos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarCreditos(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaCreditos
            Dim results() As Object = Me.Invoke("ConsultarCreditos", New Object() {usuario, password})
            Return CType(results(0),RespuestaCreditos)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarCreditosAsync(ByVal usuario As String, ByVal password As String)
            Me.ConsultarCreditosAsync(usuario, password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarCreditosAsync(ByVal usuario As String, ByVal password As String, ByVal userState As Object)
            If (Me.ConsultarCreditosOperationCompleted Is Nothing) Then
                Me.ConsultarCreditosOperationCompleted = AddressOf Me.OnConsultarCreditosOperationCompleted
            End If
            Me.InvokeAsync("ConsultarCreditos", New Object() {usuario, password}, Me.ConsultarCreditosOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarCreditosOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarCreditosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarCreditosCompleted(Me, New ConsultarCreditosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSCFDI33/ConsultarComprobantes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarComprobantes(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, ByVal fechaInicial As Date, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal fechaInicialSpecified As Boolean, ByVal fechaFinal As Date, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal fechaFinalSpecified As Boolean, ByVal filaInicial As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal filaInicialSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RespuestaReporte
            Dim results() As Object = Me.Invoke("ConsultarComprobantes", New Object() {usuario, password, fechaInicial, fechaInicialSpecified, fechaFinal, fechaFinalSpecified, filaInicial, filaInicialSpecified})
            Return CType(results(0),RespuestaReporte)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarComprobantesAsync(ByVal usuario As String, ByVal password As String, ByVal fechaInicial As Date, ByVal fechaInicialSpecified As Boolean, ByVal fechaFinal As Date, ByVal fechaFinalSpecified As Boolean, ByVal filaInicial As Integer, ByVal filaInicialSpecified As Boolean)
            Me.ConsultarComprobantesAsync(usuario, password, fechaInicial, fechaInicialSpecified, fechaFinal, fechaFinalSpecified, filaInicial, filaInicialSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarComprobantesAsync(ByVal usuario As String, ByVal password As String, ByVal fechaInicial As Date, ByVal fechaInicialSpecified As Boolean, ByVal fechaFinal As Date, ByVal fechaFinalSpecified As Boolean, ByVal filaInicial As Integer, ByVal filaInicialSpecified As Boolean, ByVal userState As Object)
            If (Me.ConsultarComprobantesOperationCompleted Is Nothing) Then
                Me.ConsultarComprobantesOperationCompleted = AddressOf Me.OnConsultarComprobantesOperationCompleted
            End If
            Me.InvokeAsync("ConsultarComprobantes", New Object() {usuario, password, fechaInicial, fechaInicialSpecified, fechaFinal, fechaFinalSpecified, filaInicial, filaInicialSpecified}, Me.ConsultarComprobantesOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarComprobantesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarComprobantesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarComprobantesCompleted(Me, New ConsultarComprobantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")>  _
    Partial Public Class RespuestaTFD33
        
        Private codigoConfirmacionField As String
        
        Private codigoRespuestaField As String
        
        Private creditosRestantesField As Integer
        
        Private creditosRestantesFieldSpecified As Boolean
        
        Private mensajeErrorField As String
        
        Private mensajeErrorDetalladoField As String
        
        Private operacionExitosaField As Boolean
        
        Private operacionExitosaFieldSpecified As Boolean
        
        Private pDFResultadoField As String
        
        Private timbreField As Timbre33
        
        Private xMLResultadoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoConfirmacion() As String
            Get
                Return Me.codigoConfirmacionField
            End Get
            Set
                Me.codigoConfirmacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoRespuesta() As String
            Get
                Return Me.codigoRespuestaField
            End Get
            Set
                Me.codigoRespuestaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreditosRestantes() As Integer
            Get
                Return Me.creditosRestantesField
            End Get
            Set
                Me.creditosRestantesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CreditosRestantesSpecified() As Boolean
            Get
                Return Me.creditosRestantesFieldSpecified
            End Get
            Set
                Me.creditosRestantesFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensajeErrorDetallado() As String
            Get
                Return Me.mensajeErrorDetalladoField
            End Get
            Set
                Me.mensajeErrorDetalladoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.operacionExitosaField
            End Get
            Set
                Me.operacionExitosaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OperacionExitosaSpecified() As Boolean
            Get
                Return Me.operacionExitosaFieldSpecified
            End Get
            Set
                Me.operacionExitosaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PDFResultado() As String
            Get
                Return Me.pDFResultadoField
            End Get
            Set
                Me.pDFResultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Timbre() As Timbre33
            Get
                Return Me.timbreField
            End Get
            Set
                Me.timbreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property XMLResultado() As String
            Get
                Return Me.xMLResultadoField
            End Get
            Set
                Me.xMLResultadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")>  _
    Partial Public Class Timbre33
        
        Private estadoField As String
        
        Private fechaTimbradoField As Date
        
        Private fechaTimbradoFieldSpecified As Boolean
        
        Private numeroCertificadoSATField As String
        
        Private selloCFDField As String
        
        Private selloSATField As String
        
        Private uUIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaTimbrado() As Date
            Get
                Return Me.fechaTimbradoField
            End Get
            Set
                Me.fechaTimbradoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FechaTimbradoSpecified() As Boolean
            Get
                Return Me.fechaTimbradoFieldSpecified
            End Get
            Set
                Me.fechaTimbradoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NumeroCertificadoSAT() As String
            Get
                Return Me.numeroCertificadoSATField
            End Get
            Set
                Me.numeroCertificadoSATField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SelloCFD() As String
            Get
                Return Me.selloCFDField
            End Get
            Set
                Me.selloCFDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SelloSAT() As String
            Get
                Return Me.selloSATField
            End Get
            Set
                Me.selloSATField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")>  _
    Partial Public Class RegistroTimbre
        
        Private estadoField As String
        
        Private fechaTimbradoField As Date
        
        Private fechaTimbradoFieldSpecified As Boolean
        
        Private noFilaField As Integer
        
        Private noFilaFieldSpecified As Boolean
        
        Private rFCEmisorField As String
        
        Private rFCReceptorField As String
        
        Private uUIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaTimbrado() As Date
            Get
                Return Me.fechaTimbradoField
            End Get
            Set
                Me.fechaTimbradoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FechaTimbradoSpecified() As Boolean
            Get
                Return Me.fechaTimbradoFieldSpecified
            End Get
            Set
                Me.fechaTimbradoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NoFila() As Integer
            Get
                Return Me.noFilaField
            End Get
            Set
                Me.noFilaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property NoFilaSpecified() As Boolean
            Get
                Return Me.noFilaFieldSpecified
            End Get
            Set
                Me.noFilaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RFCEmisor() As String
            Get
                Return Me.rFCEmisorField
            End Get
            Set
                Me.rFCEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RFCReceptor() As String
            Get
                Return Me.rFCReceptorField
            End Get
            Set
                Me.rFCReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")>  _
    Partial Public Class RespuestaReporte
        
        Private listaComprobantesField() As RegistroTimbre
        
        Private mensajeErrorField As String
        
        Private operacionExitosaField As Boolean
        
        Private operacionExitosaFieldSpecified As Boolean
        
        Private totalComprobantesPeriodoField As Integer
        
        Private totalComprobantesPeriodoFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property ListaComprobantes() As RegistroTimbre()
            Get
                Return Me.listaComprobantesField
            End Get
            Set
                Me.listaComprobantesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.operacionExitosaField
            End Get
            Set
                Me.operacionExitosaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OperacionExitosaSpecified() As Boolean
            Get
                Return Me.operacionExitosaFieldSpecified
            End Get
            Set
                Me.operacionExitosaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalComprobantesPeriodo() As Integer
            Get
                Return Me.totalComprobantesPeriodoField
            End Get
            Set
                Me.totalComprobantesPeriodoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TotalComprobantesPeriodoSpecified() As Boolean
            Get
                Return Me.totalComprobantesPeriodoFieldSpecified
            End Get
            Set
                Me.totalComprobantesPeriodoFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")>  _
    Partial Public Class DetallesPaqueteCreditos
        
        Private enUsoField As Boolean
        
        Private enUsoFieldSpecified As Boolean
        
        Private fechaActivacionField As System.Nullable(Of Date)
        
        Private fechaActivacionFieldSpecified As Boolean
        
        Private fechaVencimientoField As System.Nullable(Of Date)
        
        Private fechaVencimientoFieldSpecified As Boolean
        
        Private paqueteField As String
        
        Private timbresField As Integer
        
        Private timbresFieldSpecified As Boolean
        
        Private timbresRestantesField As Integer
        
        Private timbresRestantesFieldSpecified As Boolean
        
        Private timbresUsadosField As Integer
        
        Private timbresUsadosFieldSpecified As Boolean
        
        Private vigenteField As Boolean
        
        Private vigenteFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property EnUso() As Boolean
            Get
                Return Me.enUsoField
            End Get
            Set
                Me.enUsoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property EnUsoSpecified() As Boolean
            Get
                Return Me.enUsoFieldSpecified
            End Get
            Set
                Me.enUsoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FechaActivacion() As System.Nullable(Of Date)
            Get
                Return Me.fechaActivacionField
            End Get
            Set
                Me.fechaActivacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FechaActivacionSpecified() As Boolean
            Get
                Return Me.fechaActivacionFieldSpecified
            End Get
            Set
                Me.fechaActivacionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FechaVencimiento() As System.Nullable(Of Date)
            Get
                Return Me.fechaVencimientoField
            End Get
            Set
                Me.fechaVencimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FechaVencimientoSpecified() As Boolean
            Get
                Return Me.fechaVencimientoFieldSpecified
            End Get
            Set
                Me.fechaVencimientoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Paquete() As String
            Get
                Return Me.paqueteField
            End Get
            Set
                Me.paqueteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Timbres() As Integer
            Get
                Return Me.timbresField
            End Get
            Set
                Me.timbresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TimbresSpecified() As Boolean
            Get
                Return Me.timbresFieldSpecified
            End Get
            Set
                Me.timbresFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TimbresRestantes() As Integer
            Get
                Return Me.timbresRestantesField
            End Get
            Set
                Me.timbresRestantesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TimbresRestantesSpecified() As Boolean
            Get
                Return Me.timbresRestantesFieldSpecified
            End Get
            Set
                Me.timbresRestantesFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TimbresUsados() As Integer
            Get
                Return Me.timbresUsadosField
            End Get
            Set
                Me.timbresUsadosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TimbresUsadosSpecified() As Boolean
            Get
                Return Me.timbresUsadosFieldSpecified
            End Get
            Set
                Me.timbresUsadosFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Vigente() As Boolean
            Get
                Return Me.vigenteField
            End Get
            Set
                Me.vigenteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property VigenteSpecified() As Boolean
            Get
                Return Me.vigenteFieldSpecified
            End Get
            Set
                Me.vigenteFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")>  _
    Partial Public Class RespuestaCreditos
        
        Private mensajeErrorField As String
        
        Private operacionExitosaField As Boolean
        
        Private operacionExitosaFieldSpecified As Boolean
        
        Private paquetesField() As DetallesPaqueteCreditos
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.operacionExitosaField
            End Get
            Set
                Me.operacionExitosaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OperacionExitosaSpecified() As Boolean
            Get
                Return Me.operacionExitosaFieldSpecified
            End Get
            Set
                Me.operacionExitosaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property Paquetes() As DetallesPaqueteCreditos()
            Get
                Return Me.paquetesField
            End Get
            Set
                Me.paquetesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")>  _
    Partial Public Class RespuestaEstatusCancelacionAsincrona
        
        Private estatusField As String
        
        Private mensajeErrorField As String
        
        Private operacionExitosaField As Boolean
        
        Private operacionExitosaFieldSpecified As Boolean
        
        Private referenciaField As String
        
        Private xMLAcuseField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Estatus() As String
            Get
                Return Me.estatusField
            End Get
            Set
                Me.estatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.operacionExitosaField
            End Get
            Set
                Me.operacionExitosaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OperacionExitosaSpecified() As Boolean
            Get
                Return Me.operacionExitosaFieldSpecified
            End Get
            Set
                Me.operacionExitosaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Referencia() As String
            Get
                Return Me.referenciaField
            End Get
            Set
                Me.referenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property XMLAcuse() As String
            Get
                Return Me.xMLAcuseField
            End Get
            Set
                Me.xMLAcuseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")>  _
    Partial Public Class RespuestaCancelacionAsincrona
        
        Private detallesCancelacionField() As DetalleCancelacion
        
        Private mensajeErrorField As String
        
        Private operacionExitosaField As Boolean
        
        Private operacionExitosaFieldSpecified As Boolean
        
        Private referenciaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property DetallesCancelacion() As DetalleCancelacion()
            Get
                Return Me.detallesCancelacionField
            End Get
            Set
                Me.detallesCancelacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.operacionExitosaField
            End Get
            Set
                Me.operacionExitosaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OperacionExitosaSpecified() As Boolean
            Get
                Return Me.operacionExitosaFieldSpecified
            End Get
            Set
                Me.operacionExitosaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Referencia() As String
            Get
                Return Me.referenciaField
            End Get
            Set
                Me.referenciaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")>  _
    Partial Public Class DetalleCancelacion
        
        Private codigoResultadoField As String
        
        Private mensajeResultadoField As String
        
        Private uUIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoResultado() As String
            Get
                Return Me.codigoResultadoField
            End Get
            Set
                Me.codigoResultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensajeResultado() As String
            Get
                Return Me.mensajeResultadoField
            End Get
            Set
                Me.mensajeResultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")>  _
    Partial Public Class RespuestaCancelacion
        
        Private detallesCancelacionField() As DetalleCancelacion
        
        Private mensajeErrorField As String
        
        Private mensajeErrorDetalladoField As String
        
        Private operacionExitosaField As Boolean
        
        Private operacionExitosaFieldSpecified As Boolean
        
        Private xMLAcuseField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property DetallesCancelacion() As DetalleCancelacion()
            Get
                Return Me.detallesCancelacionField
            End Get
            Set
                Me.detallesCancelacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensajeErrorDetallado() As String
            Get
                Return Me.mensajeErrorDetalladoField
            End Get
            Set
                Me.mensajeErrorDetalladoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.operacionExitosaField
            End Get
            Set
                Me.operacionExitosaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OperacionExitosaSpecified() As Boolean
            Get
                Return Me.operacionExitosaFieldSpecified
            End Get
            Set
                Me.operacionExitosaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property XMLAcuse() As String
            Get
                Return Me.xMLAcuseField
            End Get
            Set
                Me.xMLAcuseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub TimbrarCFDICompletedEventHandler(ByVal sender As Object, ByVal e As TimbrarCFDICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TimbrarCFDICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTFD33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTFD33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub CancelarCFDICompletedEventHandler(ByVal sender As Object, ByVal e As CancelarCFDICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarCFDICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCancelacion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCancelacion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub CancelacionAsincronaCompletedEventHandler(ByVal sender As Object, ByVal e As CancelacionAsincronaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelacionAsincronaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCancelacionAsincrona
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCancelacionAsincrona)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub EstatusCancelacionAsincronaCompletedEventHandler(ByVal sender As Object, ByVal e As EstatusCancelacionAsincronaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EstatusCancelacionAsincronaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaEstatusCancelacionAsincrona
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaEstatusCancelacionAsincrona)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ObtenerPDFCompletedEventHandler(ByVal sender As Object, ByVal e As ObtenerPDFCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtenerPDFCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTFD33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTFD33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ObtenerAcuseEnvioCompletedEventHandler(ByVal sender As Object, ByVal e As ObtenerAcuseEnvioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtenerAcuseEnvioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTFD33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTFD33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ObtenerAcuseCancelacionCompletedEventHandler(ByVal sender As Object, ByVal e As ObtenerAcuseCancelacionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtenerAcuseCancelacionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTFD33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTFD33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub CambiarPasswordCompletedEventHandler(ByVal sender As Object, ByVal e As CambiarPasswordCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CambiarPasswordCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTFD33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTFD33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ConsultarComplementoTimbreCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarComplementoTimbreCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarComplementoTimbreCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTFD33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTFD33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ConsultarTimbrePorReferenciaCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarTimbrePorReferenciaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarTimbrePorReferenciaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTFD33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTFD33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ConsultarCreditosCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarCreditosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarCreditosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCreditos
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCreditos)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ConsultarComprobantesCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarComprobantesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarComprobantesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaReporte
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaReporte)
            End Get
        End Property
    End Class
End Namespace
