//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class cDescuento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cDescuento()
        {
            this.tConvenioEdoCta = new HashSet<tConvenioEdoCta>();
            this.tDescuentoAsignado = new HashSet<tDescuentoAsignado>();
            this.tRecibo = new HashSet<tRecibo>();
        }
    
        public int Id { get; set; }
        public string Clave { get; set; }
        public int Ejercicio { get; set; }
        public string Descripcion { get; set; }
        public string Autorizacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public Nullable<decimal> AnticipadoImpuesto { get; set; }
        public Nullable<decimal> AnticipadoAdicional { get; set; }
        public Nullable<decimal> AnticipadoLimpieza { get; set; }
        public Nullable<decimal> AnticipadoRecoleccion { get; set; }
        public Nullable<decimal> AnticipadoDap { get; set; }
        public Nullable<decimal> ActualImpuesto { get; set; }
        public Nullable<decimal> ActualAdicional { get; set; }
        public Nullable<decimal> ActualRecargo { get; set; }
        public Nullable<decimal> ActualLImpieza { get; set; }
        public Nullable<decimal> ActualRecoleccion { get; set; }
        public Nullable<decimal> ActualDap { get; set; }
        public Nullable<decimal> Diferencia { get; set; }
        public Nullable<decimal> DiferenciaRecargo { get; set; }
        public Nullable<decimal> Rezago { get; set; }
        public Nullable<decimal> RezagoRecargo { get; set; }
        public Nullable<decimal> RezagoAdicional { get; set; }
        public Nullable<decimal> Basegravable { get; set; }
        public Nullable<decimal> Multas { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Ejecucion { get; set; }
        public Nullable<decimal> Honorarios { get; set; }
        public Nullable<decimal> AnticipadoInfraestructura { get; set; }
        public Nullable<decimal> Infraestructura { get; set; }
        public bool Activo { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual cUsuarios cUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tConvenioEdoCta> tConvenioEdoCta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDescuentoAsignado> tDescuentoAsignado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRecibo> tRecibo { get; set; }
    }
}
