//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPrepoliza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPrepoliza()
        {
            this.tPrepolizaDetalle = new HashSet<tPrepolizaDetalle>();
            this.tPrepolizaRecibo = new HashSet<tPrepolizaRecibo>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaPrePoliza { get; set; }
        public string Descripcion { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public Nullable<decimal> ImporteDescuentoTotal { get; set; }
        public Nullable<decimal> ImporteDescuentoAntTotal { get; set; }
        public bool Activo { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual cUsuarios cUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPrepolizaDetalle> tPrepolizaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPrepolizaRecibo> tPrepolizaRecibo { get; set; }
    }
}
