//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReciboFacturaCancelada
    {
        public int idRecibo { get; set; }
        public string fecha { get; set; }
        public string motivo { get; set; }
        public string emisorRFC { get; set; }
        public string receptorRFC { get; set; }
        public Nullable<double> total { get; set; }
        public string estatusUUID { get; set; }
        public string UUID { get; set; }
        public string modulus { get; set; }
        public string xml { get; set; }
    
        public virtual tRecibo tRecibo { get; set; }
    }
}
