//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReciboDetalle
    {
        public int Id { get; set; }
        public int IdRecibo { get; set; }
        public int IdConcepto { get; set; }
        public int IdControlSistema { get; set; }
        public decimal ImporteNeto { get; set; }
        public decimal ImporteDescuento { get; set; }
        public decimal ImporteAdicional { get; set; }
        public decimal ImporteTotal { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> DescuentoDecretoPorcentaje { get; set; }
        public Nullable<int> DescuentoEspecialPorcentaje { get; set; }
        public int IdConceptoRef { get; set; }
        public bool Activo { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual cConcepto cConcepto { get; set; }
        public virtual cControlSistema cControlSistema { get; set; }
        public virtual cUsuarios cUsuarios { get; set; }
        public virtual tRecibo tRecibo { get; set; }
    }
}
