//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBuscarPredioContDom
    {
        public int IdPredio { get; set; }
        public string ClavePredial { get; set; }
        public int IdContribuyente { get; set; }
        public string NombreCompleto { get; set; }
        public int IdColonia { get; set; }
        public string Domicilio { get; set; }
    }
}
