//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPredioMovimiento
    {
        public string Clave_Catastral { get; set; }
        public Nullable<decimal> ClaveNumerica { get; set; }
        public string Nombre_Propietario { get; set; }
        public string Domicilio_Predio { get; set; }
        public string Domicilio_Notificacion { get; set; }
        public string Localidad { get; set; }
        public string Movimiento_Hecho { get; set; }
        public Nullable<double> Superficie_Terreno { get; set; }
        public Nullable<double> Valor_Terreno { get; set; }
        public Nullable<double> Superficie_Construccion { get; set; }
        public double Valor_Construccion { get; set; }
        public System.DateTime Fecha_Avaluo { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public System.DateTime Fecha_Notificacion { get; set; }
        public double Base_Gravable { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaMov { get; set; }
        public int Recibo { get; set; }
        public decimal Importe_Pagado { get; set; }
        public string Origen { get; set; }
        public int IdPredio { get; set; }
        public int IdColonia { get; set; }
        public int IdFraccionamiento { get; set; }
        public int IdTipoPredio { get; set; }
    }
}
