//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReciboMetodoPago
    {
        public int Id { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string EstadoRecibo { get; set; }
        public string Tipo { get; set; }
        public string Contribuyente { get; set; }
        public int IdCajero { get; set; }
        public string Cajero { get; set; }
        public int IdUsuarioCancela { get; set; }
        public string UsuarioCancela { get; set; }
        public decimal TotalPagado { get; set; }
        public Nullable<int> IdMetodoPagoFinal { get; set; }
        public string MetodoPagoFinal { get; set; }
        public Nullable<decimal> ImporteMetodo { get; set; }
        public string AutorizacionFinal { get; set; }
        public string OperadoraFinal { get; set; }
        public int IdPredio { get; set; }
        public string ClavePredial { get; set; }
        public string CveMetodoPagoFinal { get; set; }
    }
}
