//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTabularIngresos
    {
        public int Recibo { get; set; }
        public string ClavePredial { get; set; }
        public Nullable<decimal> ClaveNumerica { get; set; }
        public int IdPredio { get; set; }
        public string Contribuyente { get; set; }
        public string direccion { get; set; }
        public int IdColonia { get; set; }
        public string NombreColonia { get; set; }
        public string TipoPredio { get; set; }
        public int IdTipoPredio { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int IdStatusPredio { get; set; }
        public string EstatusPredio { get; set; }
        public string ExcentoPago { get; set; }
        public System.DateTime FechaAvaluo { get; set; }
        public Nullable<double> SuperficieTerreno { get; set; }
        public Nullable<double> SuperficieConstruccion { get; set; }
        public double ValorConstruccion { get; set; }
        public Nullable<double> ValorTerreno { get; set; }
        public double ValorCatastral { get; set; }
        public int IdCondominio { get; set; }
        public string CondominioDescripcion { get; set; }
        public int UltBimPagado { get; set; }
        public int UltEjercicioPagado { get; set; }
        public int UltBimPagadoSM { get; set; }
        public int UltEjercicioPagadoSM { get; set; }
        public string EstatusRecibo { get; set; }
        public System.DateTime FechaPago { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Periodo { get; set; }
        public int IdMesa { get; set; }
        public string NombreMesa { get; set; }
        public string NombreConcepto { get; set; }
        public int Cantidad { get; set; }
        public decimal ImporteNeto { get; set; }
        public decimal ImporteDescuento { get; set; }
        public decimal ImporteTotal { get; set; }
        public int IdTipoTramite { get; set; }
        public string TipoTramite { get; set; }
    }
}
