//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTramite
    {
        public string ClavePredial { get; set; }
        public string NombreAdquiriente { get; set; }
        public string TipoAvaluo { get; set; }
        public string NombreValuador { get; set; }
        public string NumeroEscritura { get; set; }
        public Nullable<System.DateTime> FechaOperacion { get; set; }
        public Nullable<double> ValorCatastral { get; set; }
        public Nullable<double> ValorComercial { get; set; }
        public Nullable<double> ValorFiscal { get; set; }
        public Nullable<double> ValorOperacion { get; set; }
        public string Notaria { get; set; }
        public int Id { get; set; }
        public Nullable<int> IdPredrio { get; set; }
        public bool Activo { get; set; }
        public string Status { get; set; }
        public string Periodo { get; set; }
        public Nullable<decimal> Adeudo { get; set; }
        public int IdTipoTramite { get; set; }
    }
}
